name: GitHub Actions Demo
on: 
  push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:          
         # - run: echo "tada The job was automatically triggered by a ${{ github.event_name }} event."
         # - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
         # - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code - test
      uses: actions/checkout@v2
    - run: mvn compile

    - name: deploy
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_CDA_PRIVATE_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.CDA_EC2_HOST }}
        if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)
    - name: authentification
      run: rsync ./foo/ user@remote:bar/
    - name: blah    
      run: |
        scp ./target/spring-petclinic-2.5.0-SNAPSHOT.jar ${{ secrets.CDA_EC2_HOST }}:petclinic.jar
        java -jar petclinic.jar --server.port=8083
