name: GitHub Actions Demo
on: [push]
jobs:
 # test:
 #  runs-on: ubuntu-latest
 #  steps:
 #    - name: Check out repository code - test
 #      uses: actions/checkout@v2
 #    - run: mvn test
 
  buildAndDeploy:
      runs-on: ubuntu-latest
      steps:
        - name: build
          uses: actions/checkout@v2
        - run : mvn package
        - name: deploy  
          uses: kielabokkie/ssh-key-and-known-hosts-action@v1
          with:
            ssh-private-key: ${{ secrets.SSH_CDA_PRIVATE_KEY }}
            ssh-host: ${{ secrets.CDA_EC2_HOST }}
        - run: |
            scp ./target/spring-petclinic-2.5.0-SNAPSHOT.jar ${{ secrets.USER_NAME }}@${{ secrets.CDA_EC2_HOST }}:petclinic.jar
            ssh ${{ secrets.USER_NAME }}@${{ secrets.CDA_EC2_HOST }} 'java -jar petclinic.jar --server.port=8083'
